THINGSPEAK_CHANNEL_ID="3124874"
THINGSPEAK_READ_API_KEY="K1KWJUWOZ9EZMUOS"

SUPABASE_URL="https://ragapkdlgtpmumwlzphs.supabase.co"
SUPABASE_SERVICE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhZ2Fwa2RsZ3RwbXVtd2x6cGhzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MjYxNjAwMywiZXhwIjoyMDc4MTkyMDAzfQ.UTu1ldJK-llqtFGtcD26AKfdflXOriZ-pmuSEGhI9KE"

SUPABASE_USER_ID="03180adf-b8cd-452e-b9ce-d5918d1b9683"

DATA_ENCRYPTION_KEY="DVCN1nPH_HxqpYIfv-vCpsV8ol2NW4hu7EpJHbDjZdw="


